name: Push Docker Image
on:
    push:
        branches:
            - main
    release:
        types: [published]

env:
    DOCKER_BASE_NAME: docker.pkg.github.com/t1nyb0x/discord-twitter-embed-rx

jobs:
    hadolint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 1

            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

    push-image:
        runs-on: ubuntu-latest
        needs: hadolint
        steps:
            - uses: actions/checkout@v4

            - name: Set Env
              run: |
                if [ "${{ github.event_name }}" = 'release' ]; then
                    export TAG_NAME="${{ github.event.release.tag_name }}"
                else
                    export TAG_NAME="latest"
                fi
                echo "PKG_TAG"=${DOCKER_BASE_NAME}:${TAG_NAME} >> ${GITHUB_ENV}

            - name: Build Image
              run: |
                docker build . -t "${PKG_TAG}"
        
            - name: Login to Registries
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u  t1nyb0x --password-stdin
        
            - name: Push to GitHub Packages
              run: docker push ${PKG_TAG}
